version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: yourpassword
    ports:
      - 27017:27017

  chat:
    build: .
    restart: always
    depends_on:
      - mongo
    environment:
      MONGO_USER: admin
      MONGO_PASS: yourpassword
      MONGO_HOST: mongo
    ports:
      - 8501:8501

